### ISSUE TITLE
Head of empty list error in tests

### ISSUE THREAD

**Issue by TheDIM47** [flink-extended/flink-scala-api#13]
Hi. Got "Head of empty list" in simple test:

https://github.com/flink-extended/flink-scala-api/compare/master...TheDIM47:flink-scala-api:head-of-empty-list-demo

```
head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at scala.collection.immutable.Nil$.head(List.scala:661)
	at scala.collection.StrictOptimizedLinearSeqOps$$anon$1.next(LinearSeq.scala:267)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1249)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
	at scala.collection.AbstractIterable.addString(Iterable.scala:933)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
	at scala.collection.AbstractIterable.mkString(Iterable.scala:933)
	at scala.collection.Iterable.toString(Iterable.scala:78)
	at scala.collection.Iterable.toString$(Iterable.scala:78)
	at scala.collection.Seq.toString(Seq.scala:43)
	at scala.collection.Seq.toString$(Seq.scala:43)
	at scala.collection.AbstractSeq.toString(Seq.scala:1189)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:172)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1249)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
	at scala.collection.AbstractIterator.addString(Iterator.scala:1300)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
	at scala.collection.AbstractIterator.mkString(Iterator.scala:1300)
	at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
	at org.apache.flink.api.ProcessFunctionTest$DataPackage.toString(ProcessFunctionTest.scala:28)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:172)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1246)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1241)
	at scala.collection.AbstractIterable.addString(Iterable.scala:933)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1191)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1189)
	at scala.collection.AbstractIterable.mkString(Iterable.scala:933)
	at scala.collection.Iterable.toString(Iterable.scala:78)
	at scala.collection.Iterable.toString$(Iterable.scala:78)
	at scala.collection.Seq.toString(Seq.scala:43)
	at scala.collection.Seq.toString$(Seq.scala:43)
	at scala.collection.AbstractSeq.toString(Seq.scala:1189)
	at org.scalactic.ColCompatHelper$.className(ColCompatHelper.scala:35)
	at org.scalactic.Prettifier$$anon$2.apply(Prettifier.scala:228)
	at org.scalatest.FailureMessages$.wasNotEqualTo(FailureMessages.scala:907)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.$anonfun$shouldBe$67(Matchers.scala:7021)
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:391)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7021)
	at org.apache.flink.api.ProcessFunctionTest.$anonfun$new$1(ProcessFunctionTest.scala:22)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1812)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1810)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1822)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1822)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1804)
	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1880)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1880)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1879)
	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1114)
	at org.scalatest.Suite.run$(Suite.scala:1096)
	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1925)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1925)
	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1923)
	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:47)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1321)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1315)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1315)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:43)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:26)
```

**Comment by novakov-alexey** [comment]
checking.

**Comment by novakov-alexey** [comment]
@TheDIM47 thanks for the report. Flink TestHarness is a tricky one. I could make it work with such changes:

```scala
  private def prepareTestHarness[D <: DataPackage, R <: DataPackage](
      processFunction: KeyedProcessFunction[String, D, R],
      serializer: TypeSerializer[R]
  ): KeyedOneInputStreamOperatorTestHarness[String, D, R] = {
    val harness = new KeyedOneInputStreamOperatorTestHarness[String, D, R](
      new KeyedProcessOperator[String, D, R](
        processFunction
      ),
      k => k.id,
      TypeInformation.of(classOf[String]),
      1,
      1,
      0
    )
    harness.setup(serializer)
    harness.open()
    harness
  }

// then in test case

val serializer = deriveTypeInformation[DataPackage].createSerializer(ExecutionConfig())
val harness    = prepareTestHarness(new SimpleFunction(), serializer)
```

**Comment by novakov-alexey** [comment]
If it works for you, can you add this test as a PR please?
